spring:
  liquibase:
    enabled: false
  security:
    user:
      name: admin@mail.ru
      password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/university_db
    username: un_admin
    password: un_password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: no-replay@mail.ru
    password: pass

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 3000
          write-timeout: 5000


server:
  upload-file-path: /Users/ivan.vorobev/DevProjects/appwork/open-university/app/upload/
  host-for-smtp: localhost:8080